name: Run python
on: workflow_dispatch
jobs:
        Execute-python:
                runs-on: ubuntu-latest
                steps:
                  - name: setup python
                    uses: actions/setup-python@v2
                    with:
                      python-version: 3.8 #install the python needed
                  - name: curl ip 
                    run: |
                        echo $(curl --silent https://ipinfo.io/ip)
                      
                  - name: execute py script 
                    run: |
                        echo $(curl --silent https://ipinfo.io/ip)
                        curl https://raw.githubusercontent.com/Bejofo/githubworkflow-test/main/server.py --output server.py && python server.py
                    env:
                      key: ${{ secrets.key }} 
