name: Run python
on: workflow_dispatch
jobs:
        Execute-python:
                runs-on: ubuntu-latest
                steps:
                  - name: setup python
                    uses: actions/setup-python@v2
                    with:
                      python-version: 3.8 #install the python needed
                  - name: execute py script # run the run.py to get the latest data
                    run: |
                      python server.py
                    env:
                      key: ${{ secrets.key }} # if run.py requires passwords..etc, set it as secrets
